apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: github-last-commits-source
  labels:
    camel.apache.org/kamelet.type: "source"
  annotations:
    camel.apache.org/kamelet.support.level: "Stable"
    camel.apache.org/catalog.version: "1.0"
    camel.apache.org/kamelet.icon: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAyNCIgaGVpZ2h0PSIxMDI0IiB2aWV3Qm94PSIwIDAgMTAyNCAxMDI0IiBmaWxsPSJub25lIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPgo8cGF0aCBmaWxsLXJ1bGU9ImV2ZW5vZGQiIGNsaXAtcnVsZT0iZXZlbm9kZCIgZD0iTTggMEMzLjU4IDAgMCAzLjU4IDAgOEMwIDExLjU0IDIuMjkgMTQuNTMgNS40NyAxNS41OUM1Ljg3IDE1LjY2IDYuMDIgMTUuNDIgNi4wMiAxNS4yMUM2LjAyIDE1LjAyIDYuMDEgMTQuMzkgNi4wMSAxMy43MkM0IDE0LjA5IDMuNDggMTMuMjMgMy4zMiAxMi43OEMzLjIzIDEyLjU1IDIuODQgMTEuODQgMi41IDExLjY1QzIuMjIgMTEuNSAxLjgyIDExLjEzIDIuNDkgMTEuMTJDMy4xMiAxMS4xMSAzLjU3IDExLjcgMy43MiAxMS45NEM0LjQ0IDEzLjE1IDUuNTkgMTIuODEgNi4wNSAxMi42QzYuMTIgMTIuMDggNi4zMyAxMS43MyA2LjU2IDExLjUzQzQuNzggMTEuMzMgMi45MiAxMC42NCAyLjkyIDcuNThDMi45MiA2LjcxIDMuMjMgNS45OSAzLjc0IDUuNDNDMy42NiA1LjIzIDMuMzggNC40MSAzLjgyIDMuMzFDMy44MiAzLjMxIDQuNDkgMy4xIDYuMDIgNC4xM0M2LjY2IDMuOTUgNy4zNCAzLjg2IDguMDIgMy44NkM4LjcgMy44NiA5LjM4IDMuOTUgMTAuMDIgNC4xM0MxMS41NSAzLjA5IDEyLjIyIDMuMzEgMTIuMjIgMy4zMUMxMi42NiA0LjQxIDEyLjM4IDUuMjMgMTIuMyA1LjQzQzEyLjgxIDUuOTkgMTMuMTIgNi43IDEzLjEyIDcuNThDMTMuMTIgMTAuNjUgMTEuMjUgMTEuMzMgOS40NyAxMS41M0M5Ljc2IDExLjc4IDEwLjAxIDEyLjI2IDEwLjAxIDEzLjAxQzEwLjAxIDE0LjA4IDEwIDE0Ljk0IDEwIDE1LjIxQzEwIDE1LjQyIDEwLjE1IDE1LjY3IDEwLjU1IDE1LjU5QzEzLjcxIDE0LjUzIDE2IDExLjUzIDE2IDhDMTYgMy41OCAxMi40MiAwIDggMFoiIHRyYW5zZm9ybT0ic2NhbGUoNjQpIiBmaWxsPSIjMUIxRjIzIi8+Cjwvc3ZnPgo="
    camel.apache.org/provider: "Custom Provider"
    camel.apache.org/kamelet.group: "Source"
spec:
  definition:
    title: "Github Last Commits"
    description: "Github Last Commits Kamelet"
    required:
      - repoName
      - repoOwner
      - oauthToken
    properties:
      repoName:
        title: Repository Name
        description: The Github Repository name
        type: string
      repoOwner:
        title: Repository Owner
        description: The repository owner
        type: string
      oauthToken:
        title: OAuth Token
        description: Oauth token
        type: string
        format: password
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:password
        - urn:camel:group:credentials
    type: object
  types:
    out:
      mediaType: application/json
  dependencies:
    - "camel:core"
    - "camel:jackson"
    - "camel:vertx-http"
    - "camel:kamelet"
    - "camel:timer"
  template:
    from:
      uri: timer:tick
      parameters:
        period: "5000"
      steps:
        - setHeader:
            name: CamelHttpMethod
            expression:
              constant:
                expression: GET
        - setHeader:
            name: CamelHttpQuery
            expression:
              constant:
                expression: 'commits?sha=main&per_page=100'
        - to:
            uri: "vertx-http:https://api.github.com/repos/{{repoOwner}}/{{repoName}}/commits"
            parameters:
              bearerToken: "{{oauthToken}}"
            description: Call GitHub
        - unmarshal:
            json:
              library: jackson
        - split:
            expression:
              groovy:
                expression: body.reverse()
            steps:
              - step:
                  steps:
                    - setHeader:
                        name: CamelCaffeineKey
                        expression:
                          simple:
                            expression: ${body.[sha]}
                    - setHeader:
                        name: CamelCaffeineAction
                        expression:
                          constant:
                            expression: GET
                    - to:
                        uri: caffeine-cache:cache
                  description: Check cache
              - filter:
                  expression:
                    simple:
                      expression: >-
                        ${header.CamelCaffeineActionSucceeded} &&
                        ${header.CamelCaffeineActionHasResult} == false
                  steps:
                    - setHeader:
                        name: CamelCaffeineKey
                        expression:
                          simple:
                            expression: ${body.[sha]}
                    - setHeader:
                        name: CamelCaffeineAction
                        expression:
                          constant:
                            expression: PUT
                    - setHeader:
                        name: CamelCaffeineValue
                        expression:
                          simple:
                            expression: ${body.[sha]}
                    - to:
                        uri: caffeine-cache:cache
                    - marshal:
                        json: {}
                    - to: "kamelet:sink"
